variables:
  GIT_SUBMODULE_STRATEGY: recursive

.hugo:
  image: registry.gitlab.com/pages/hugo:latest
  stage: deploy
  script:
    - hugo ${HUGO_FLAGS} -b ${HUGO_BASEURL}
  artifacts:
    paths:
      - public

pages:
  extends: .hugo
  only: ['master']
  needs: []
  variables:
    # Include drafts
    HUGO_FLAGS: --minify
    HUGO_BASEURL: https://www.taricorp.net/

build:
  extends: .hugo
  stage: build
  needs: []
  variables:
    HUGO_FLAGS: -D
    HUGO_BASEURL: https://beta.taricorp.net/

deploy:
  stage: deploy
  needs: [build]
  image: 'instrumentisto/rsync-ssh'
  variables:
    GIT_STRATEGY: none
  before_script:
    - umask 077
    - mkdir -p ~/.ssh
    - umask 133
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - umask 022
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d | ssh-add -
  script:
    - 'rsync -rvzz --delete-after ./public/ tari@weaver.taricorp.net:'
