# Site settings
title: タリ
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beta.taricorp.net" # the base hostname & protocol for your site
twitter_username: pmarheine
github_username:  tari
sidebar: ["sidebar/foo"]

permalink: '/:year/:title.html'
paginate: 10
excerpt_separator: "<!-- more -->"
date_format: "%Y-%m-%d"

# Build settings
markdown: redcarpet-pygments

redcarpet:
    extensions: ["superscript", "footnotes"]
