languageCode = "en-us"
title = "タリ"
theme = "hugo-flex"

enableRobotsTXT = true
rssLimit = 20
summaryLength = 100

# With RSS output format below, write the main feed to /feed.xml
# rather than /index.xml
[outputs]
home = [ "RSS", "HTML" ]

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[markup]
  [markup.highlight]
    lineNos = true
    style = "github"
  [markup.goldmark.renderer]
    unsafe = true

[permalinks]
posts = "/:year/:slug/"
projects = "/projects/:slug/"
essays = "/essays/:slug/"

[params]
  summaries = true
  color = "black"
  width = "60rem"
  css = [ "tcn.css" ]
  footer = """\
             Reluctantly powered by atomic badgers. \
             Contents licensed under \
             <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">\
             <img src="https://licensebuttons.net/l/by-sa/4.0/80x15.png" alt="CC-BY-SA" />\
             </a> unless otherwise noted.\
           """

[menu]
  nav = [
    { name = "Blog", url = "posts/", weight = 1},
    { name = "Projects", url = "projects/", weight = 2},
    { name = "RSS", url = "feed.xml", weight = 100 },
  ]
  
