languageCode = "en-us"
title = "タリ"
baseurl = "http://beta.taricorp.net"
theme = "twentyfourteen"
PygmentsCodeFences = true
pygmentsstyle = "default"
relativeURLs = true

[permalinks]
posts = "/:year/:slug/"
