languageCode = "en-us"
title = "タリ"
theme = "twentyfourteen"
PygmentsCodeFences = true
pygmentsstyle = "default"
relativeURLs = true

[permalinks]
posts = "/:year/:slug/"
projects = "/projects/:slug/"
essays = "/essays/:slug/"
