# Should match the backend app's configuration on gitlab
site_url: https://beta.taricorp.net
publish_mode: editorial_workflow

collections:
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/posts"
    # Create page bundles
    slug: "{{fields.slug}}"
    path: "{{year}}/{{slug}}/index"
    # Put media next to post data
    media_folder: ""
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # TODO: make a collection for categories and make this a relation
      - {label: "Categories", name: "categories", widget: "list"}
      # TODO: as above, make a collection?
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    files:
      - name: "404"
        label: "404"
        file: "content/404.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "About"
        label: "About"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "project"
    label: "Project"
    folder: "content/projects"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish date", name: "date", widget: "datetime"}
      - {label: "Last updated", name: "updated", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "essay"
    label: "Essay"
    folder: "content/essays"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish date", name: "date", widget: "datetime"}
      - {label: "Last updated", name: "updated", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}


media_folder: "static/images"
public_folder: "images"

backend:
  name: gitlab
  repo: taricorp/taricorp.net
  branch: master
  auth_type: pkce
  app_id: 04b2000c5aa2db7aab7220725e264c643cd6e3b7ecd28fd4a7493c9bf02e634f
